[package]
name = "rust-pairwise-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
