[package]
name = "tango-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
tango-bench = { path="../tango-bench" }

[dev-dependencies]
criterion = "0.5.1"
ordsearch = { version = "0.2.*", features = ["nightly"] }
num-traits = "^0.2"

[[bench]]
name = "ordsearch"
harness = false
