name: Test

on: push

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-apple-darwin
            os: macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Install Cargo Export
        run: cargo install cargo-export --version 0.2.0

      - name: Restore ./target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: Cargo/${{ runner.os }}

      - name: Run Tests
        run: |
          cargo test

      - name: Exporting Branch Benchmarks
        run: cargo export target/benchmarks -- bench --bench=tango

      - name: Switching to Master
        uses: actions/checkout@v3
        with:
          ref: dev
          path: main-branch

      - name: Exporting Main Benchmarks
        working-directory: main-branch
        run: cargo export target/benchmarks -- bench --bench=tango

      - name: Run Benchmarks
        run: |
          set -eo pipefail

          target/benchmarks/tango compare main-branch/target/benchmarks/tango -v -t 1000 --fail-threshold 10 \
            | tee target/benchmark.txt

      - name: Archive Benchmarks Results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark.txt
          path: target/benchmark.txt
